const { test, expect } = require("@playwright/test");
const { randEmail, randFullName } = require("@ngneat/falso");

const { BasePage } = require("../../pages/BasePage.js");
const { HomePage } = require("../../pages/HomePage.js");
const { LoginPage } = require("../../pages/LoginPage.js");
const { ContactPage } = require("../../pages/ContactPage.js");
const testData = JSON.parse(
  JSON.stringify(require("../../testData/credentials.json")),
);

test("Contact us form should be submitted successfully", async ({ page }) => {
  const basePage = new BasePage(page);
  await basePage.goTo();
  const homePage = new HomePage(page);
  await homePage.navigateToLogin();
  const loginPage = new LoginPage(page);
  await loginPage.loginIn(testData.userEmail, testData.password);
  await homePage.navigateToContactUs(page);
  const contactPage = new ContactPage(page);
  await contactPage.verifyContactPageVisible();
  await contactPage.submitContactForm(
    randFullName(),
    randEmail(),
    "Automation contact test",
    "This message was generated by a Playwright automated test.",
  );
  await contactPage.verifySuccessMessage();
});
