const { test, expect } = require("../../fixtures/uiFixtures.js");
const { randEmail, randFullName } = require("@ngneat/falso");
const testData = require("../../testData/credentials.json");

test.describe("TS-004 - UI - Contact Us", () => {
  test(
    "TC-004 - Contact us form should be submitted successfully",
    { tag: "@regression" },
    async ({ homePage, loginPage, contactPage }) => {
      await homePage.navigateToLogin();
      await loginPage.loginIn(testData.userEmail, testData.password);
      await homePage.navigateToContactUs();
      await contactPage.verifyContactPageVisible();
      await contactPage.submitContactForm(
        randFullName(),
        randEmail(),
        "Automation contact test",
        "This message was generated by a Playwright automated test.",
      );
      await contactPage.verifySuccessMessage();
    },
  );
});
