const { test, expect } = require("../../fixtures/uiFixtures.js");
const { randEmail, randFullName } = require("@ngneat/falso");
const testData = require("../../testData/credentials.json");

test.describe("TS-001 - UI Test Suite", () => {
  test(
    "TC-001 - Add one product to cart",
    async ({ homePage, loginPage, productsPage, cartPage }) => {
      await homePage.navigateToLogin();
      await loginPage.loginIn(testData.userEmail, testData.password);
      await homePage.navigateToProducts();
      await productsPage.verifyAllProductsVisible();
      await productsPage.searchProduct(testData.product);
      await productsPage.verifySearchedProductsVisible();
      await productsPage.addProductToCart(testData.product);
      await cartPage.verifyItemInCart(testData.product);
    },
  );

  test(
    "TC-002 - Correct Login",
    async ({ homePage, loginPage }) => {
      await homePage.navigateToLogin();
      await loginPage.loginIn(testData.userEmail, testData.password);
    },
  );

  test(
    "TC-003 - Invalid Login",
    async ({ homePage, loginPage }) => {
      await homePage.navigateToLogin();
      await loginPage.wrongLogin(
        testData.wrongUserEmail,
        testData.wrongPassword,
      );
    },
  );

  test(
    "TC-004 - Contact us form should be submitted successfully",
    async ({ homePage, loginPage, contactPage }) => {
      await homePage.navigateToLogin();
      await loginPage.loginIn(testData.userEmail, testData.password);
      await homePage.navigateToContactUs();
      await contactPage.verifyContactPageVisible();
      await contactPage.submitContactForm(
        randFullName(),
        randEmail(),
        "Automation contact test",
        "This message was generated by a Playwright automated test.",
      );
      await contactPage.verifySuccessMessage();
    },
  );

  test(
    "TC-005 - Register a new user",
    async ({ homePage, loginPage, signupPage }) => {
      await homePage.navigateToLogin();
      await loginPage.waitForNetworkIdle();
      await loginPage.register();
      await signupPage.waitForNetworkIdle();
      await signupPage.createAccount();
      await signupPage.deleteAccount();
    },
  );
});
